radianHub/Philadelphia-Works--Inc.

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Launchpad__Stage__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-011881 to Integration

- force-app/main/default/layouts/Launchpad__Applicant_Tracking__c-Launchpad__Hire Layout.layout-meta.xml
- force-app/main/default/layouts/Launchpad__Applicant_Tracking__c-Program Application Layout.layout-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Age_at_Start_of_Program__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Program__c/fields/Application_Close_Date__c.field-meta.xml
> [DevOps Center] Merge WI-011921 to Integration

- force-app/main/default/lwc/providerSearch/providerSearch.html
- force-app/main/default/lwc/providerSearch/providerSearch.js
> [DevOps Center] Merge WI-011931 to Integration

- force-app/main/default/classes/ProviderSearchController.cls
- force-app/main/default/classes/ProviderSearchControllerTest.cls
- force-app/main/default/lwc/multiSelectCombobox/multiSelectCombobox.js
- force-app/main/default/lwc/providerMap/providerMap.js
- force-app/main/default/lwc/providerSearch/providerSearch.html
- force-app/main/default/lwc/providerSearch/providerSearch.js
- force-app/main/default/lwc/providerSearch/providerSearch.js-meta.xml
- force-app/main/default/lwc/providerTile/providerTile.html
- force-app/main/default/lwc/providerTile/providerTile.js
> [DevOps Center] Merge WI-011942 to Integration

- force-app/main/default/lwc/providerSearch/providerSearch.js-meta.xml
- force-app/main/default/objects/Launchpad__Job__c/fieldSets/Default_Provider_Search_Field_Set.fieldSet-meta.xml
> [DevOps Center] Merge WI-011945 to Integration

- .forceignore
- force-app/main/default/classes/JobApplicationTriggerHandler.cls
- force-app/main/default/classes/JobApplicationTriggerHandler.cls-meta.xml
- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Previous_Stage__c.field-meta.xml
- force-app/main/default/triggers/JobApplicationTrigger.trigger
- force-app/main/default/triggers/JobApplicationTrigger.trigger-meta.xml
> [DevOps Center] Merge WI-011933 to Integration

- force-app/main/default/lwc/providerSearch/providerSearch.html
- force-app/main/default/lwc/providerSearch/providerSearch.js
> [DevOps Center] Merge WI-011954 to Integration

- force-app/main/default/classes/DocumentChecklistController.cls
- force-app/main/default/classes/DocumentChecklistControllerTest.cls
- force-app/main/default/objects/Launchpad__Document__c/fields/Launchpad__Status__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Document__c/fields/Rejection_Reason__c.field-meta.xml
> [DevOps Center] Merge WI-011966 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Consent_to_Request_Clearance__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Income_Attestation__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Media_Picture_Release__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Release_of_Information__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Willing_to_accept_an_unselected_program__c.field-meta.xml
> [DevOps Center] Merge WI-011969 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/classes/CreateApplicationControllerTest.cls
- force-app/main/default/lwc/createApplication/createApplication.html
- force-app/main/default/lwc/createApplication/createApplication.js
- force-app/main/default/lwc/providerMap/providerMap.js
- force-app/main/default/lwc/providerSearch/providerSearch.css
- force-app/main/default/lwc/providerSearch/providerSearch.html
- force-app/main/default/lwc/providerSearch/providerSearch.js
- force-app/main/default/lwc/providerSelectionCart/providerSelectionCart.css
- force-app/main/default/lwc/providerSelectionCart/providerSelectionCart.html
- force-app/main/default/lwc/providerSelectionCart/providerSelectionCart.js
- force-app/main/default/lwc/providerSelectionCart/providerSelectionCart.js-meta.xml
- force-app/main/default/lwc/providerTile/providerTile.html
- force-app/main/default/lwc/providerTile/providerTile.js
> [DevOps Center] Merge WI-011971 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
> [DevOps Center] Merge WI-011974 to Integration

- force-app/main/default/lwc/youthApplication/youthApplication.css
- force-app/main/default/lwc/youthApplication/youthApplication.html
- force-app/main/default/lwc/youthApplication/youthApplication.js
- force-app/main/default/lwc/youthApplication/youthApplication.js-meta.xml
> [DevOps Center] Merge WI-011976 to Integration

- force-app/main/default/classes/UniversalApp.cls
> [DevOps Center] Merge WI-011980 to Integration

- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_Section_1.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_Section_2.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_Section_3.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_Section_4.fieldSet-meta.xml
> [DevOps Center] Merge WI-011968 to UAT

- force-app/main/default/lwc/youthApplication/youthApplication.css
- force-app/main/default/lwc/youthApplication/youthApplication.html
- force-app/main/default/lwc/youthApplication/youthApplication.js
- force-app/main/default/lwc/youthApplication/youthApplication.js-meta.xml
> [DevOps Center] Merge WI-011976 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Applicant_s_Emergency_Contact_Info.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Consent_to_Request_Clearance.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Consents.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Demographic_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Explanation_of_Attestations.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Health_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Household_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Household_Information_2.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Household_Information_3.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Household_Information_4.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Income_Attestation.fieldSet-meta.xml
> [DevOps Center] Merge WI-011981 to Integration

- force-app/main/default/globalValueSets/Schools.globalValueSet-meta.xml
> [DevOps Center] Merge WI-011987 to Integration

- force-app/main/default/globalValueSets/Schools.globalValueSet-meta.xml
> [DevOps Center] Merge WI-011992 to Integration

- force-app/main/default/globalValueSets/Schools.globalValueSet-meta.xml
> [DevOps Center] Merge WI-011992 to UAT

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_PageProperties.Launchpad__My_Profile_Education_Employment_Info.md-meta.xml
- force-app/main/default/lwc/createApplication/createApplication.js
- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantCommunity_MyProfile_Demograph.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantCommunity_MyProfile_Education.fieldSet-meta.xml
> [DevOps Center] Merge WI-011998 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_State__c.field-meta.xml
> [DevOps Center] Merge WI-011999 to Integration

- force-app/main/default/classes/ProviderSearchController.cls
- force-app/main/default/classes/ProviderSearchControllerTest.cls
- force-app/main/default/customMetadata/Contact_Job_Eligibility_Map.Age.md-meta.xml
- force-app/main/default/customMetadata/Contact_Job_Eligibility_Map.Gender.md-meta.xml
- force-app/main/default/customMetadata/Contact_Job_Eligibility_Map.Grade.md-meta.xml
- force-app/main/default/customMetadata/Contact_Job_Eligibility_Map.School.md-meta.xml
- force-app/main/default/lwc/providerSearch/providerSearch.css
- force-app/main/default/lwc/providerSearch/providerSearch.html
- force-app/main/default/lwc/providerSearch/providerSearch.js
- force-app/main/default/objects/Contact_Job_Eligibility_Map__mdt/Contact_Job_Eligibility_Map__mdt.object-meta.xml
- force-app/main/default/objects/Contact_Job_Eligibility_Map__mdt/fields/Contact_Field_API_Name__c.field-meta.xml
- force-app/main/default/objects/Contact_Job_Eligibility_Map__mdt/fields/Job_Field_API_Name__c.field-meta.xml
> [DevOps Center] Merge WI-012003 to Integration

- force-app/main/default/objects/Launchpad__Job__c/fieldSets/Default_Logged_In_User_Provider_Search.fieldSet-meta.xml
> [DevOps Center] Merge WI-012004 to Integration

- force-app/main/default/classes/UniversalApp.cls
> [DevOps Center] Merge WI-012010 to Integration

- force-app/main/default/flows/Consent_Form_Email_to_Job_Applications.flow-meta.xml
> [DevOps Center] Merge WI-012011 to Integration

- force-app/main/default/classes/JobApplicationTriggerHandler.cls
- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Launchpad__Stage__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Potential_Duplicates.listView-meta.xml
> [DevOps Center] Merge WI-012013 to Integration

- force-app/main/default/customMetadata/Launchpad__ParticipantRegistration_FieldProperties.Launchpad__Mailing_State.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantRegistration_FieldProperties.Launchpad__Mailing_Zip_Code.md-meta.xml
- force-app/main/default/objects/Contact/validationRules/State_Validation.validationRule-meta.xml
- force-app/main/default/objects/Contact/validationRules/Zip_Code_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_Zip_Code__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/State_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Zip_Code_Validation.validationRule-meta.xml
> [DevOps Center] Merge WI-012018 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_PageProperties.Launchpad__My_Profile_Education_Employment_Info.md-meta.xml
- force-app/main/default/lwc/createApplication/createApplication.js
- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantCommunity_MyProfile_Demograph.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantCommunity_MyProfile_Education.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_State__c.field-meta.xml
> [DevOps Center] Merge WI-011999 to UAT

- force-app/main/default/customMetadata/Launchpad__ParticipantRegistration_FieldProperties.Launchpad__Mailing_State.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantRegistration_FieldProperties.Launchpad__Mailing_Zip_Code.md-meta.xml
- force-app/main/default/objects/Contact/validationRules/State_Validation.validationRule-meta.xml
- force-app/main/default/objects/Contact/validationRules/Zip_Code_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_Zip_Code__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/State_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Zip_Code_Validation.validationRule-meta.xml
> [DevOps Center] Merge WI-012018 to UAT

- force-app/main/default/classes/UniversalApp.cls
> [DevOps Center] Merge WI-012019 to Integration

- force-app/main/default/triggers/ProgramTrigger.trigger
- force-app/main/default/triggers/ProgramTrigger.trigger-meta.xml
> [DevOps Center] Merge WI-012021 to Integration

- force-app/main/default/customMetadata/Universal_App_Section.Applicant_s_Emergency_Contact_Info.md-meta.xml
- force-app/main/default/customMetadata/Universal_App_Section.Applicant_s_Guardian_Information.md-meta.xml
- force-app/main/default/lwc/univApp/univApp.js
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Applicant_s_Guardian_Information.fieldSet-meta.xml
> [DevOps Center] Merge WI-012022 to Integration

- force-app/main/default/classes/JobApplicationTriggerHandler.cls
- force-app/main/default/classes/UniversalApp.cls
> [DevOps Center] Merge WI-012024 to Integration

- force-app/main/default/objects/Contact/validationRules/MobilePhone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Contact/validationRules/Phone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_Tax_Id__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Applicant_Phone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Emergency_Contact_Phone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Guardian_Phone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/SSN_Validation.validationRule-meta.xml
> [DevOps Center] Merge WI-012025 to Integration

- force-app/main/default/lwc/univApp/univApp.html
- force-app/main/default/lwc/univApp/univApp.js
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Phone_Number__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_DOB_Readonly__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_Tax_Id__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Guardian_Phone_Number__c.field-meta.xml
> [DevOps Center] Merge WI-012026 to Integration

- force-app/main/default/triggers/ProgramTrigger.trigger
- force-app/main/default/triggers/ProgramTrigger.trigger-meta.xml
> [DevOps Center] Merge WI-012021 to UAT

- force-app/main/default/customMetadata/Universal_App_Section.Applicant_s_Emergency_Contact_Info.md-meta.xml
- force-app/main/default/customMetadata/Universal_App_Section.Applicant_s_Guardian_Information.md-meta.xml
- force-app/main/default/lwc/univApp/univApp.html
- force-app/main/default/lwc/univApp/univApp.js
- force-app/main/default/objects/Contact/validationRules/MobilePhone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Contact/validationRules/Phone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Applicant_s_Guardian_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Phone_Number__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_DOB_Readonly__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_Tax_Id__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Guardian_Phone_Number__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Applicant_Phone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Emergency_Contact_Phone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Guardian_Phone_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/SSN_Validation.validationRule-meta.xml
> [DevOps Center] Merge WI-012026 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Age_at_Start_of_Program__c.field-meta.xml
> [DevOps Center] Merge WI-012027 to UAT

- force-app/main/default/classes/UniversalApp.cls
> [DevOps Center] Merge WI-012028 to Integration

- force-app/main/default/classes/UniversalApp.cls
> [DevOps Center] Merge WI-012028 to UAT

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Country_of_Nationality__c.field-meta.xml
> [DevOps Center] Merge WI-012029 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Country_of_Nationality__c.field-meta.xml
> [DevOps Center] Merge WI-012029 to UAT

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/classes/CreateApplicationControllerTest.cls
- force-app/main/default/flows/Daily_Notification_Check_Email.flow-meta.xml
- force-app/main/default/objects/Contact/fields/Active_Program_Notification_Date_Today__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Youth_Notification_Date_is_Today__c.field-meta.xml
> [DevOps Center] Merge WI-012034 to Integration

- force-app/main/default/email/unfiled$public/Document_Rejection.email
- force-app/main/default/email/unfiled$public/Document_Rejection.email-meta.xml
- force-app/main/default/flows/Send_Document_Rejection_Email.flow-meta.xml
- force-app/main/default/objects/Launchpad__Document__c/fields/Applicant_Name__c.field-meta.xml
- force-app/main/default/workflows/Launchpad__Document__c.workflow-meta.xml
> [DevOps Center] Merge WI-012035 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Emergency_Contact_Exclusive_Email.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Guardian_and_Applicant_Exclusive_Emails.validationRule-meta.xml
> [DevOps Center] Merge WI-012038 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
> [DevOps Center] Merge WI-012040 to Integration

- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_Section_3.fieldSet-meta.xml
> [DevOps Center] Merge WI-012043 to Integration

- force-app/main/default/classes/ContactTriggerHandler.cls
> [DevOps Center] Merge WI-012044 to Integration

- force-app/main/default/classes/DocumentChecklistController.cls
- force-app/main/default/classes/ProviderApplicantsController.cls
- force-app/main/default/classes/ProviderJobsController.cls
- force-app/main/default/classes/ProviderJobsController.cls-meta.xml
- force-app/main/default/classes/ProviderSearchController.cls
- force-app/main/default/lwc/applicantBulkUpdateModal/applicantBulkUpdateModal.html
- force-app/main/default/lwc/applicantBulkUpdateModal/applicantBulkUpdateModal.js
- force-app/main/default/lwc/applicantBulkUpdateModal/applicantBulkUpdateModal.js-meta.xml
- force-app/main/default/lwc/applicantDatatable/customApplicantName.html
- force-app/main/default/lwc/applicantModal/applicantModal.css
- force-app/main/default/lwc/applicantModal/applicantModal.html
- force-app/main/default/lwc/applicantModal/applicantModal.js
- force-app/main/default/lwc/documentChecklist/documentChecklist.html
- force-app/main/default/lwc/documentChecklist/documentChecklist.js
- force-app/main/default/lwc/documentChecklist/documentChecklist.js-meta.xml
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem.html
- force-app/main/default/lwc/jobModal/jobModal.css
- force-app/main/default/lwc/jobModal/jobModal.html
- force-app/main/default/lwc/jobModal/jobModal.js
- force-app/main/default/lwc/jobModal/jobModal.js-meta.xml
- force-app/main/default/lwc/providerApplicants/providerApplicants.css
- force-app/main/default/lwc/providerApplicants/providerApplicants.html
- force-app/main/default/lwc/providerApplicants/providerApplicants.js
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Provider_Choice__c.field-meta.xml
> [DevOps Center] Merge WI-012046 to Integration

- force-app/main/default/classes/ProviderJobsControllerTest.cls
- force-app/main/default/classes/ProviderJobsControllerTest.cls-meta.xml
- force-app/main/default/classes/ProviderSearchControllerTest.cls
- force-app/main/default/lwc/jobDatatable/customJobName.html
- force-app/main/default/lwc/jobDatatable/jobDatatable.html
- force-app/main/default/lwc/jobDatatable/jobDatatable.js
- force-app/main/default/lwc/jobDatatable/jobDatatable.js-meta.xml
- force-app/main/default/lwc/jobModal/jobModal.js
- force-app/main/default/lwc/providerJobs/providerJobs.css
- force-app/main/default/lwc/providerJobs/providerJobs.html
- force-app/main/default/lwc/providerJobs/providerJobs.js
- force-app/main/default/lwc/providerJobs/providerJobs.js-meta.xml
- force-app/main/default/objects/Launchpad__Job__c/fieldSets/Provider_Jobs_List_View_Details_Fields.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Job__c/fieldSets/Provider_Jobs_List_View_Edit_Fields.fieldSet-meta.xml
> [DevOps Center] Merge WI-012047 to Integration

- force-app/main/default/classes/ProviderApplicantsController.cls
- force-app/main/default/lwc/applicantTile/applicantTile.html
- force-app/main/default/lwc/applicantTile/applicantTile.js
- force-app/main/default/lwc/providerApplicants/providerApplicants.js
> [DevOps Center] Merge WI-012048 to Integration

- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_DuplicateCheck.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fields/Middle_Name__c.field-meta.xml
> [DevOps Center] Merge WI-012050 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Middle_Name__c.field-meta.xml
> [DevOps Center] Merge WI-012051 to Integration

- force-app/main/default/classes/UniversalApp.cls
> [DevOps Center] Merge WI-012052 to Integration

- force-app/main/default/objects/Launchpad__Job__c/fieldSets/Default_Logged_In_User_Provider_Search.fieldSet-meta.xml
> [DevOps Center] Merge WI-012004 to UAT

- force-app/main/default/email/unfiled$public/Document_Rejection.email
- force-app/main/default/email/unfiled$public/Document_Rejection.email-meta.xml
- force-app/main/default/flows/Send_Document_Rejection_Email.flow-meta.xml
- force-app/main/default/objects/Launchpad__Document__c/fields/Applicant_Name__c.field-meta.xml
- force-app/main/default/workflows/Launchpad__Document__c.workflow-meta.xml
> [DevOps Center] Merge WI-012035 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Emergency_Contact_Exclusive_Email.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Guardian_and_Applicant_Exclusive_Emails.validationRule-meta.xml
> [DevOps Center] Merge WI-012038 to UAT

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/classes/CreateApplicationControllerTest.cls
- force-app/main/default/flows/Daily_Notification_Check_Email.flow-meta.xml
- force-app/main/default/objects/Contact/fields/Active_Program_Notification_Date_Today__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Youth_Notification_Date_is_Today__c.field-meta.xml
> [DevOps Center] Merge WI-012040 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Passed_Reason__c.field-meta.xml
> [DevOps Center] Merge WI-012041 to UAT

- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_Section_3.fieldSet-meta.xml
> [DevOps Center] Merge WI-012043 to UAT

- force-app/main/default/matchingRules/Contact.matchingRule-meta.xml
> [DevOps Center] Merge WI-012057 to Integration

- force-app/main/default/globalValueSets/Schools.globalValueSet-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Guardian.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Contractor.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Employer.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Job_Seeker.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Partners.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Student.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Training_Provider.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Young_Adult.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Staff.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Supervisor.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Youth.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-012061 to Integration

- force-app/main/default/globalValueSets/Schools.globalValueSet-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Guardian.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Contractor.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Employer.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Job_Seeker.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Partners.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Student.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Training_Provider.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Young_Adult.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Staff.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Supervisor.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Youth.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-012061 to UAT

- force-app/main/default/classes/ProviderApplicantsController.cls
- force-app/main/default/lwc/applicantDatatable/applicantDatatable.js
- force-app/main/default/lwc/applicantDatatable/customApplicantName.html
- force-app/main/default/lwc/providerApplicants/providerApplicants.html
- force-app/main/default/lwc/providerApplicants/providerApplicants.js
> [DevOps Center] Merge WI-012064 to UAT

- force-app/main/default/classes/ProviderApplicantsController.cls
> [DevOps Center] Merge WI-012079 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
> [DevOps Center] Merge WI-012083 to Integration

- force-app/main/default/lwc/providerApplicants/providerApplicants.html
- force-app/main/default/lwc/providerApplicants/providerApplicants.js
> [DevOps Center] Merge WI-012087 to Integration

- force-app/main/default/lwc/providerApplicants/providerApplicants.html
- force-app/main/default/lwc/providerApplicants/providerApplicants.js
> [DevOps Center] Merge WI-012087 to UAT

- force-app/main/default/duplicateRules/Contact.Contact_Duplicate_Rule.duplicateRule-meta.xml
> [DevOps Center] Merge WI-012091 to Integration

- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_DuplicateCheck.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Job__c/fieldSets/Default_Provider_Search_Field_Set.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Job__c/fields/Program_Name__c.field-meta.xml
> [DevOps Center] Merge WI-012092 to Integration

- force-app/main/default/objects/Contact/fields/Historical_Email__c.field-meta.xml
> [DevOps Center] Merge WI-012093 to Integration

- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_DuplicateCheck.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Job__c/fieldSets/Default_Provider_Search_Field_Set.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Job__c/fields/Program_Name__c.field-meta.xml
> [DevOps Center] Merge WI-012092 to UAT

- force-app/main/default/objects/Contact/fields/Historical_Email__c.field-meta.xml
> [DevOps Center] Merge WI-012093 to UAT

- force-app/main/default/classes/ContactTriggerHandler.cls
> [DevOps Center] Merge WI-012100 to Integration

- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
> [DevOps Center] Merge WI-012102 to Integration

- force-app/main/default/flexipages/Job_Application_Record_Page1.flexipage-meta.xml
- force-app/main/default/flows/Application_After_Record_Save.flow-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Demographic_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicants_Last_Completed_Grade__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Priority_Population.listView-meta.xml
> [DevOps Center] Merge WI-012104 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Current_Employment_Status__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/All_Submitted_Applications.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Potential_Duplicates.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Priority_Population.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Provider_Selected_Applications.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_1_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_2_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_3_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_4_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_5_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Shortlisted_Applications.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-012105 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Current_Employment_Status__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/All_Submitted_Applications.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Potential_Duplicates.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Priority_Population.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Provider_Selected_Applications.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_1_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_2_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_3_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_4_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Rank_5_Apps.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/listViews/Shortlisted_Applications.listView-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-012105 to UAT

- force-app/main/default/classes/CreateApplicationController.cls
> [DevOps Center] Merge WI-012106 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
> [DevOps Center] Merge WI-012107 to Integration

- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_DuplicateCheck.fieldSet-meta.xml
> [DevOps Center] Merge WI-012108 to Integration

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Health_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Emergency_Contact_Exclusive_Email.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Guardian_and_Applicant_Exclusive_Emails.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/State_Validation.validationRule-meta.xml
> [DevOps Center] Merge WI-012110 to Integration

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Health_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Emergency_Contact_Exclusive_Email.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Guardian_and_Applicant_Exclusive_Emails.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/State_Validation.validationRule-meta.xml
> [DevOps Center] Merge WI-012110 to UAT

- force-app/main/default/customMetadata/Contact_Job_Eligibility_Map.Age.md-meta.xml
- force-app/main/default/lwc/providerSearch/providerSearch.js
- force-app/main/default/objects/Contact/fields/Age_at_Start_of_Program__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Participant_Community_Setup__c/Launchpad__Participant_Community_Setup__c.object-meta.xml
- force-app/main/default/objects/Launchpad__Participant_Community_Setup__c/fields/Program_Start_Date__c.field-meta.xml
> [DevOps Center] Merge WI-012111 to Integration

- force-app/main/default/objects/Contact/fields/Age_at_Start_of_Program__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Age_at_Start_of_Program__c.field-meta.xml
> [DevOps Center] Merge WI-012112 to Integration

- force-app/main/default/customMetadata/Contact_Job_Eligibility_Map.Age.md-meta.xml
- force-app/main/default/lwc/providerSearch/providerSearch.js
- force-app/main/default/objects/Contact/fields/Age_at_Start_of_Program__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Age_at_Start_of_Program__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Participant_Community_Setup__c/Launchpad__Participant_Community_Setup__c.object-meta.xml
- force-app/main/default/objects/Launchpad__Participant_Community_Setup__c/fields/Program_Start_Date__c.field-meta.xml
> [DevOps Center] Merge WI-012112 to UAT

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/classes/JobApplicationTriggerHandler.cls
> [DevOps Center] Merge WI-012114 to Integration

- force-app/main/default/classes/ProviderJobsController.cls
- force-app/main/default/classes/ProviderJobsControllerTest.cls
- force-app/main/default/classes/ProviderSupervisorsController.cls
- force-app/main/default/classes/ProviderSupervisorsController.cls-meta.xml
- force-app/main/default/classes/ProviderSupervisorsControllerTest.cls
- force-app/main/default/classes/ProviderSupervisorsControllerTest.cls-meta.xml
- force-app/main/default/customMetadata/Document_Checklist.C2L_PHL_Supervisor_Document_Checklist.md-meta.xml
- force-app/main/default/customMetadata/Document_Checklist_Item.Proof_of_Clearance.md-meta.xml
- force-app/main/default/lwc/jobModal/jobModal.html
- force-app/main/default/lwc/jobModal/jobModal.js
- force-app/main/default/lwc/providerJobs/providerJobs.js
- force-app/main/default/lwc/providerSupervisors/providerSupervisors.css
- force-app/main/default/lwc/providerSupervisors/providerSupervisors.html
- force-app/main/default/lwc/providerSupervisors/providerSupervisors.js
- force-app/main/default/lwc/providerSupervisors/providerSupervisors.js-meta.xml
- force-app/main/default/lwc/supervisorDatatable/customSupervisorName.html
- force-app/main/default/lwc/supervisorDatatable/supervisorDatatable.html
- force-app/main/default/lwc/supervisorDatatable/supervisorDatatable.js
- force-app/main/default/lwc/supervisorDatatable/supervisorDatatable.js-meta.xml
- force-app/main/default/lwc/supervisorModal/supervisorModal.css
- force-app/main/default/lwc/supervisorModal/supervisorModal.html
- force-app/main/default/lwc/supervisorModal/supervisorModal.js
- force-app/main/default/lwc/supervisorModal/supervisorModal.js-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Provider_Supervisors_List_View_Details.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fields/Supervisor_Clearance__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Document__c/fields/Launchpad__Type__c.field-meta.xml
> [DevOps Center] Merge WI-012097 to UAT

- force-app/main/default/classes/ContactTriggerHandler.cls
- force-app/main/default/triggers/ContactTrigger.trigger
> [DevOps Center] Merge WI-012100 to UAT

- force-app/main/default/objects/Contact/fieldSets/Launchpad__ParticipantRegistration_DuplicateCheck.fieldSet-meta.xml
> [DevOps Center] Merge WI-012108 to UAT

- force-app/main/default/classes/JobApplicationTriggerHandler.cls
- force-app/main/default/classes/UniversalApp.cls
> [DevOps Center] Merge WI-012117 to Integration

- force-app/main/default/objects/Account/fields/Supervisor__c.field-meta.xml
> [DevOps Center] Merge WI-012119 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/classes/ProviderApplicantsController.cls
- force-app/main/default/lwc/providerApplicants/providerApplicants.js
> [DevOps Center] Merge WI-012121 to Integration

- force-app/main/default/classes/CreateApplicationController.cls
- force-app/main/default/classes/ProviderApplicantsController.cls
- force-app/main/default/lwc/providerApplicants/providerApplicants.js
> [DevOps Center] Merge WI-012121 to UAT

- force-app/main/default/lwc/applicantEligibilityAlert/applicantEligibilityAlert.css
- force-app/main/default/lwc/applicantEligibilityAlert/applicantEligibilityAlert.html
- force-app/main/default/lwc/applicantEligibilityAlert/applicantEligibilityAlert.js
- force-app/main/default/lwc/applicantEligibilityAlert/applicantEligibilityAlert.js-meta.xml
- force-app/main/default/lwc/providerSearch/providerSearch.html
- force-app/main/default/lwc/providerSearch/providerSearch.js
> [DevOps Center] Merge WI-012124 to Integration

- force-app/main/default/lwc/applicantEligibilityAlert/applicantEligibilityAlert.css
- force-app/main/default/lwc/applicantEligibilityAlert/applicantEligibilityAlert.html
- force-app/main/default/lwc/applicantEligibilityAlert/applicantEligibilityAlert.js
- force-app/main/default/lwc/applicantEligibilityAlert/applicantEligibilityAlert.js-meta.xml
- force-app/main/default/lwc/providerSearch/providerSearch.html
- force-app/main/default/lwc/providerSearch/providerSearch.js
> [DevOps Center] Merge WI-012124 to UAT

- force-app/main/default/classes/ConsentFormBatchEmail.cls
- force-app/main/default/classes/ConsentFormBatchEmail.cls-meta.xml
- force-app/main/default/classes/ConsentFormBatchEmailTest.cls
- force-app/main/default/classes/ConsentFormBatchEmailTest.cls-meta.xml
- force-app/main/default/flows/Consent_Form_Email_to_Job_Applications.flow-meta.xml
> [DevOps Center] Merge WI-012126 to Integration

- force-app/main/default/lwc/documentChecklist/documentChecklist.html
- force-app/main/default/lwc/documentChecklist/documentChecklist.js
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem.html
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem.js
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem_review.html
- force-app/main/default/lwc/documentChecklistPreview/documentChecklistPreview.html
- force-app/main/default/lwc/documentChecklistPreview/documentChecklistPreview.js
- force-app/main/default/lwc/documentChecklistPreview/documentChecklistPreview.js-meta.xml
> [DevOps Center] Merge WI-012130 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
> [DevOps Center] Merge WI-012131 to Integration

- force-app/main/default/lwc/documentChecklist/documentChecklist.html
- force-app/main/default/lwc/documentChecklist/documentChecklist.js
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem.html
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem.js
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem_review.html
- force-app/main/default/lwc/documentChecklistPreview/documentChecklistPreview.html
- force-app/main/default/lwc/documentChecklistPreview/documentChecklistPreview.js
- force-app/main/default/lwc/documentChecklistPreview/documentChecklistPreview.js-meta.xml
> [DevOps Center] Merge WI-012130 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
> [DevOps Center] Merge WI-012131 to UAT

- force-app/main/default/classes/ConsentFormBatchEmail.cls
- force-app/main/default/classes/ConsentFormBatchEmail.cls-meta.xml
- force-app/main/default/classes/ConsentFormBatchEmailTest.cls
- force-app/main/default/classes/ConsentFormBatchEmailTest.cls-meta.xml
- force-app/main/default/flows/Consent_Form_Email_to_Job_Applications.flow-meta.xml
> [DevOps Center] Merge WI-012126 to UAT

- force-app/main/default/classes/UniversalApp.cls
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem_review.html
- force-app/main/default/lwc/univApp/univApp.html
- force-app/main/default/lwc/univApp/univApp.js
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Consents.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Health_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Consent_to_Request_Clearance__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Parent_s_Consent__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Consent_to_Request_Clearance_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Media_Picture_Release_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Release_of_Information_Validation.validationRule-meta.xml
> [DevOps Center] Merge WI-012132 to Integration

- force-app/main/default/classes/UniversalApp.cls
- force-app/main/default/lwc/documentChecklistItem/documentChecklistItem_review.html
- force-app/main/default/lwc/univApp/univApp.html
- force-app/main/default/lwc/univApp/univApp.js
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Consents.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Health_Information.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Consent_to_Request_Clearance__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Parent_s_Consent__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Consent_to_Request_Clearance_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Media_Picture_Release_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Release_of_Information_Validation.validationRule-meta.xml
> [DevOps Center] Merge WI-012132 to UAT

- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Launchpad__First_Name.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Launchpad__Last_Name.md-meta.xml
> [DevOps Center] Merge WI-012133 to Integration

- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Launchpad__First_Name.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Launchpad__Last_Name.md-meta.xml
> [DevOps Center] Merge WI-012133 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Parent_s_Consent__c.field-meta.xml
> [DevOps Center] Merge WI-012135 to UAT

- force-app/main/default/flows/Consent_Form_To_Guardian.flow-meta.xml
> [DevOps Center] Merge WI-012137 to Integration

- force-app/main/default/navigationMenus/EmployerDefault.navigationMenu-meta.xml
> [DevOps Center] Merge WI-012143 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Last_Completed_Grade__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Preferred_Pronoun__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-012144 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Last_Completed_Grade__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Preferred_Pronoun__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-012144 to UAT

- force-app/main/default/flows/Update_Contacts_When_Ready_for_Reassignment.flow-meta.xml
> [DevOps Center] Merge WI-012145 to Integration

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Current_Most_Recent_School__c.field-meta.xml
> [DevOps Center] Merge WI-012146 to Integration

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Current_Most_Recent_School__c.field-meta.xml
> [DevOps Center] Merge WI-012146 to UAT

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/objects/Contact/fields/Current_Most_Recent_School__c.field-meta.xml
> [DevOps Center] Merge WI-012147 to Integration

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/objects/Contact/fields/Current_Most_Recent_School__c.field-meta.xml
> [DevOps Center] Merge WI-012147 to UAT

- force-app/main/default/classes/UniversalApp_Test.cls
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Emergency_Contact_Exclusive_Email.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Guardian_and_Applicant_Exclusive_Emails.validationRule-meta.xml
> [DevOps Center] Merge WI-012151 to Integration

- force-app/main/default/classes/JobApplicationTriggerHandler.cls
- force-app/main/default/flows/Update_Contacts_When_Ready_for_Reassignment.flow-meta.xml
> [DevOps Center] Merge WI-012152 to Integration

- force-app/main/default/customMetadata/Document_Checklist_Item.I_9.md-meta.xml
- force-app/main/default/customMetadata/Document_Checklist_Item.W_4.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Age.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Age_at_Start_of_Program.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Country_of_Nationality.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Middle_Name.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Preferred_Name.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Primary_Language_Spoken_at_Home.md-meta.xml
- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Unique_ID_SSN.md-meta.xml
- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/lwc/documentChecklistPreview/documentChecklistPreview.html
- force-app/main/default/lwc/documentChecklistPreview/documentChecklistPreview.js
- force-app/main/default/objects/Contact/fieldSets/Participant_Contact_1.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Legal_Middle_Name__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Media_Picture_Release_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Document__c/fields/Launchpad__Type__c.field-meta.xml
> [DevOps Center] Merge WI-012155 to Integration

- force-app/main/default/classes/JobApplicationTriggerHandler.cls
- force-app/main/default/triggers/JobApplicationTrigger.trigger
> [DevOps Center] Merge WI-012157 to Integration

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Participant_Contact_3.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fields/Any_other_source_of_income__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Explanation_of_Attestations__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Income__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Income_from_operation_of_a_business__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Interest_in_dividends_from_assets__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Public_Assistance_Payments__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Social_Security_or_Other_Payments__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Unemployment_or_disability_payments__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Wages_from_Employment__c.field-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Guardian.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Contractor.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Employer.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Job_Seeker.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Partners.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Student.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Training_Provider.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Launchpad__Young_Adult.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Staff.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Supervisor.recordType-meta.xml
- force-app/main/default/objects/Contact/recordTypes/Youth.recordType-meta.xml
> [DevOps Center] Merge WI-012159 to Integration

- force-app/main/default/classes/ConsentFormBatchEmail.cls
- force-app/main/default/classes/GuestUserApplicationControllerTest.cls
- force-app/main/default/classes/GuestUserApplicationControllerTest.cls-meta.xml
- force-app/main/default/classes/JobApplicationTriggerHandler.cls
> [DevOps Center] Merge WI-012161 to Integration

- force-app/main/default/navigationMenus/EmployerDefault.navigationMenu-meta.xml
> [DevOps Center] Merge WI-012143 to UAT

- force-app/main/default/flows/Consent_Form_Email_to_Job_Applications.flow-meta.xml
> [DevOps Center] Merge WI-012167 to Integration

- force-app/main/default/flows/Consent_Form_Email_to_Job_Applications.flow-meta.xml
> [DevOps Center] Merge WI-012167 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Current_Living_Situation__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-012168 to Integration

- force-app/main/default/classes/consentFormGuestController.cls
- force-app/main/default/classes/consentFormGuestController.cls-meta.xml
- force-app/main/default/lwc/consentForm/consentForm.html
- force-app/main/default/lwc/consentForm/consentForm.js
- force-app/main/default/lwc/consentForm/consentForm.js-meta.xml
> [DevOps Center] Merge WI-012174 to Integration

- force-app/main/default/classes/consentFormGuestController.cls
- force-app/main/default/classes/consentFormGuestController.cls-meta.xml
- force-app/main/default/lwc/consentForm/consentForm.html
- force-app/main/default/lwc/consentForm/consentForm.js
- force-app/main/default/lwc/consentForm/consentForm.js-meta.xml
> [DevOps Center] Merge WI-012174 to UAT

- force-app/main/default/lwc/consentForm/consentForm.js
> [DevOps Center] Merge WI-012175 to Integration

- force-app/main/default/lwc/consentForm/consentForm.js
> [DevOps Center] Merge WI-012175 to UAT

- force-app/main/default/classes/ProviderApplicantsControllerTest.cls
- force-app/main/default/classes/ProviderApplicantsControllerTest.cls-meta.xml
> [DevOps Center] Merge WI-012178 to Integration

- force-app/main/default/classes/UniversalApp_Test.cls
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Emergency_Contact_Exclusive_Email.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Guardian_and_Applicant_Exclusive_Emails.validationRule-meta.xml
> [DevOps Center] Merge WI-012151 to UAT

- force-app/main/default/classes/ProviderApplicantsControllerTest.cls
- force-app/main/default/classes/ProviderApplicantsControllerTest.cls-meta.xml
> [DevOps Center] Merge WI-012178 to UAT

- force-app/main/default/classes/ConsentFormBatchEmailTest.cls
- force-app/main/default/classes/ContactTriggerHandlerTest.cls
- force-app/main/default/classes/CreateApplicationControllerTest.cls
- force-app/main/default/classes/DocumentChecklistControllerTest.cls
- force-app/main/default/classes/GuestUserApplicationControllerTest.cls
- force-app/main/default/classes/JobApplicationConsentFormControllerTest.cls
- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
- force-app/main/default/classes/ProgramTriggerControllerTest.cls
- force-app/main/default/classes/ProviderJobsControllerTest.cls
- force-app/main/default/classes/ProviderSearchControllerTest.cls
- force-app/main/default/classes/ProviderSupervisorsControllerTest.cls
- force-app/main/default/classes/UniversalApp.cls
- force-app/main/default/classes/UniversalApp_Test.cls
> [DevOps Center] Merge WI-012180 to Integration

- force-app/main/default/classes/ConsentFormBatchEmailTest.cls
- force-app/main/default/classes/ContactTriggerHandlerTest.cls
- force-app/main/default/classes/CreateApplicationControllerTest.cls
- force-app/main/default/classes/DocumentChecklistControllerTest.cls
- force-app/main/default/classes/GuestUserApplicationControllerTest.cls
- force-app/main/default/classes/JobApplicationConsentFormControllerTest.cls
- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
- force-app/main/default/classes/ProgramTriggerControllerTest.cls
- force-app/main/default/classes/ProviderJobsControllerTest.cls
- force-app/main/default/classes/ProviderSearchControllerTest.cls
- force-app/main/default/classes/ProviderSupervisorsControllerTest.cls
- force-app/main/default/classes/UniversalApp.cls
- force-app/main/default/classes/UniversalApp_Test.cls
DevOps Center created this change request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this change request.
> [DO NOT MERGE] For DevOps Center use only - Integration to UAT

- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
> [DevOps Center] Merge WI-012185 to Integration

- force-app/main/default/flexipages/Job_Application_Record_Page1.flexipage-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Stipend__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Require_Stipend_Field.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Stipend_Type_required_at_Placed_Stage.validationRule-meta.xml
> [DevOps Center] Merge WI-012184 to Integration

- force-app/main/default/objects/Contact/fields/Historical_ID__c.field-meta.xml
> [DevOps Center] Merge WI-012088 to Integration

- force-app/main/default/objects/Contact/fields/Historical_ID__c.field-meta.xml
> [DevOps Center] Merge WI-012088 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Stipend_Type_required_at_Placed_Stage.validationRule-meta.xml
> [DevOps Center] Merge WI-012197 to Integration

- force-app/main/default/flows/Application_After_Record_Save.flow-meta.xml
- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/flows/Update_Contacts_When_Ready_for_Reassignment.flow-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Participant_Contact_1.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fields/Social_Security_Number__c.field-meta.xml
- force-app/main/default/objects/Contact/validationRules/SSN_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Income_Attestation__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge WI-012200 to Integration

- force-app/main/default/customMetadata/Universal_App_Section.Contact_Income_Attestation.md-meta.xml
- force-app/main/default/customMetadata/Universal_App_Section.Income_Attestation.md-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Income_Attestation_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Require_Stipend_Field.validationRule-meta.xml
> [DevOps Center] Merge WI-012201 to Integration

- force-app/main/default/customMetadata/Universal_App_Section.Self_Attestations.md-meta.xml
> [DevOps Center] Merge WI-012202 to Integration

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/flows/Update_Contacts_When_Ready_for_Reassignment.flow-meta.xml
- force-app/main/default/objects/Contact/fields/Media_Picture_Release__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Parents_Consent__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Release_of_Information__c.field-meta.xml
> [DevOps Center] Merge WI-012207 to Integration

- force-app/main/default/classes/ConsentFormBatchEmail.cls
- force-app/main/default/email/unfiled$public/Consent_Form_Email_Template.email
- force-app/main/default/email/unfiled$public/Consent_Form_Email_Template.email-meta.xml
- force-app/main/default/email/unfiled$public/Youth_Portal_New_Member_Welcome_Email.email
- force-app/main/default/email/unfiled$public/Youth_Portal_New_Member_Welcome_Email.email-meta.xml
> [DevOps Center] Merge WI-012208 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Email_Address__c.field-meta.xml
> [DevOps Center] Merge WI-012209 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Applicant_s_Email_Address__c.field-meta.xml
> [DevOps Center] Merge WI-012209 to UAT

- force-app/main/default/customMetadata/Universal_App_Section.Contact_Income_Attestation.md-meta.xml
- force-app/main/default/customMetadata/Universal_App_Section.Income_Attestation.md-meta.xml
- force-app/main/default/flexipages/Job_Application_Record_Page1.flexipage-meta.xml
- force-app/main/default/flows/Application_After_Record_Save.flow-meta.xml
- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
- force-app/main/default/flows/Contact_After_Record_Save.flow-meta.xml
- force-app/main/default/flows/Update_Contacts_When_Ready_for_Reassignment.flow-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Basic_Personal_Information.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Participant_Contact_1.fieldSet-meta.xml
- force-app/main/default/objects/Contact/fields/Media_Picture_Release__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Parents_Consent__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Release_of_Information__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/Social_Security_Number__c.field-meta.xml
- force-app/main/default/objects/Contact/validationRules/SSN_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Income_Attestation__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fields/Stipend__c.field-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Hire.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__Interview.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Income_Attestation_Validation.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Require_Stipend_Field.validationRule-meta.xml
- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Stipend_Type_required_at_Placed_Stage.validationRule-meta.xml
> [DevOps Center] Merge WI-012207 to UAT

- force-app/main/default/customMetadata/Universal_App_Section.Self_Attestations.md-meta.xml
> [DevOps Center] Merge WI-012202 to UAT

- force-app/main/default/classes/JobApplicationTriggerHandler.cls
- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
- force-app/main/default/triggers/JobApplicationTrigger.trigger
> [DevOps Center] Merge WI-012210 to Integration

- force-app/main/default/flows/Update_Contacts_When_Ready_for_Reassignment.flow-meta.xml
> [DevOps Center] Merge WI-012211 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/fieldSets/Demographic_Information.fieldSet-meta.xml
> [DevOps Center] Merge WI-012215 to Integration

- force-app/main/default/customMetadata/Launchpad__ParticipantCommunity_FieldProperties.Grade.md-meta.xml
- force-app/main/default/objects/Contact/fieldSets/Participant_Contact_1.fieldSet-meta.xml
- force-app/main/default/objects/Launchpad__Document__c/fields/Approved_by_Intermediary__c.field-meta.xml
> [DevOps Center] Merge WI-012217 to Integration

- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
> [DevOps Center] Merge WI-012222 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/recordTypes/Launchpad__New_Application.recordType-meta.xml
> [DevOps Center] Merge UAT to Staging

- force-app/main/default/flows/Application_After_Record_Save_Contact_Fields_Update.flow-meta.xml
> [DevOps Center] Merge WI-012224 to Integration

- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
> [DevOps Center] Merge WI-012223 to Integration

- force-app/main/default/classes/JobApplicationTriggerHandlerTest.cls
> [DevOps Center] Merge WI-012223 to UAT

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Stipend_Type_required_at_Placed_Stage.validationRule-meta.xml
> [DevOps Center] Merge version v2 into Production

- force-app/main/default/classes/JobApplicationTriggerHandler.cls
> [DevOps Center] Merge WI-012225 to Integration

- force-app/main/default/objects/Launchpad__Applicant_Tracking__c/validationRules/Stipend_Type_required_at_Placed_Stage.validationRule-meta.xml
> [DevOps Center] Merge version v3 into Production

- force-app/main/default/classes/DocumentChecklistControllerTest.cls
- force-app/main/default/classes/ProviderApplicantsControllerTest.cls
> [DevOps Center] Merge WI-012248 to Integration
